export const maquetas = [
    {
        id: 1,
        estadio: 'La Bombonera',
        club: 'Boca Juniors',
        escala: '1:500',
        precio: 189000,
        stock: 7,
        edicion: 'Edicion Club',
        material: 'Resina + base acrilica',
        descripcion: 'Una pieza con volumenes marcados, tribunas iconicas y terminacion ideal para escritorio o living.',
        imagen: 'assets/img/products/boca-juniors/la-bombonera/cover.webp',
        galeria: [
            'assets/img/products/boca-juniors/la-bombonera/cover.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-01.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-02.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-03.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-04.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-05.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-06.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-07.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-08.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-09.webp',
            'assets/img/products/boca-juniors/la-bombonera/gallery-10.webp'
        ]
    },
    {
        id: 2,
        estadio: 'Mas Monumental',
        club: 'River Plate',
        escala: '1:600',
        precio: 205000,
        stock: 5,
        edicion: 'Serie Arquitectura',
        material: 'Polimero tecnico',
        descripcion: 'Modelo pensado para destacar la amplitud del anillo superior y el nuevo despliegue del estadio.',
        imagen: 'assets/img/products/river-plate/mas-monumental/cover.png',
        galeria: [
            'assets/img/products/river-plate/mas-monumental/cover.png',
            'assets/img/products/river-plate/mas-monumental/gallery-01.jpg',
            'assets/img/products/river-plate/mas-monumental/gallery-02.jpg',
            'assets/img/products/river-plate/mas-monumental/gallery-03.jpg',
            'assets/img/products/river-plate/mas-monumental/gallery-04.jpg',
            'assets/img/products/river-plate/mas-monumental/gallery-05.jpg'
        ],
        referenciaPersonalizada: false
    },
    {
        id: 3,
        estadio: 'El Cilindro',
        club: 'Racing Club',
        escala: '1:550',
        precio: 176000,
        stock: 6,
        edicion: 'Hincha Edition',
        material: 'Resina microtexturada',
        descripcion: 'Una maqueta pensada para resaltar la forma del estadio y su identidad inconfundible en exhibicion.',
        imagen: 'assets/img/products/racing-club/el-cilindro/cover.jpg',
        galeria: [
            'assets/img/products/racing-club/el-cilindro/cover.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-01.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-02.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-03.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-04.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-05.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-06.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-07.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-08.jpg',
            'assets/img/products/racing-club/el-cilindro/gallery-09.jpg'
        ],
        destacado: true,
        referenciaPersonalizada: false
    },
    {
        id: 4,
        estadio: 'Libertadores de America',
        club: 'Independiente',
        escala: '1:500',
        precio: 181000,
        stock: 4,
        edicion: 'Rojo Legendario',
        material: 'Composito premium',
        descripcion: 'Una pieza sobria y potente, con tribunas definidas y base lista para sumar a cualquier coleccion.',
        imagen: 'assets/img/products/independiente/libertadores-de-america/cover.webp',
        galeria: [
            'assets/img/products/independiente/libertadores-de-america/cover.webp',
            'assets/img/products/independiente/libertadores-de-america/gallery-01.webp',
            'assets/img/products/independiente/libertadores-de-america/gallery-02.webp',
            'assets/img/products/independiente/libertadores-de-america/gallery-03.webp',
            'assets/img/products/independiente/libertadores-de-america/gallery-04.webp',
            'assets/img/products/independiente/libertadores-de-america/gallery-05.webp',
            'assets/img/products/independiente/libertadores-de-america/gallery-06.webp',
            'assets/img/products/independiente/libertadores-de-america/gallery-07.webp'
        ]
    },
    {
        id: 5,
        estadio: 'Campeon del Siglo',
        club: 'Penarol',
        escala: '1:600',
        precio: 214000,
        stock: 3,
        edicion: 'Matchday Edition',
        material: 'Poliresina pintada a mano',
        descripcion: 'Detalles de fachada, estructura y plateas en una pieza compacta para colecciones con caracter.',
        imagen: 'assets/img/products/penarol/campeon-del-siglo/cover.webp',
        galeria: [
            'assets/img/products/penarol/campeon-del-siglo/cover.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-01.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-02.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-03.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-04.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-05.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-06.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-07.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-08.webp',
            'assets/img/products/penarol/campeon-del-siglo/gallery-09.webp'
        ]
    },
    {
        id: 6,
        estadio: 'Nuevo Francisco Urbano',
        club: 'Deportivo Moron',
        escala: '1:600',
        precio: 198000,
        stock: 8,
        edicion: 'Sudamericana',
        material: 'Resina satinada',
        descripcion: 'Version premium del estadio de Moron, con foco en sus tribunas, fachada y lectura general del volumen.',
        imagen: 'assets/img/products/deportivo-moron/nuevo-francisco-urbano/cover.webp',
        galeria: [
            'assets/img/products/deportivo-moron/nuevo-francisco-urbano/cover.webp',
            'assets/img/products/deportivo-moron/nuevo-francisco-urbano/gallery-01.webp',
            'assets/img/products/deportivo-moron/nuevo-francisco-urbano/gallery-02.webp',
            'assets/img/products/deportivo-moron/nuevo-francisco-urbano/gallery-03.webp',
            'assets/img/products/deportivo-moron/nuevo-francisco-urbano/gallery-04.webp',
            'assets/img/products/deportivo-moron/nuevo-francisco-urbano/gallery-05.webp'
        ]
    },
    {
        id: 7,
        estadio: 'Julio Cesar Villagra',
        club: 'Belgrano de Cordoba',
        escala: '1:650',
        precio: 224000,
        stock: 5,
        edicion: 'Iconos Del Mundo',
        material: 'Polimero tecnico',
        descripcion: 'Una pieza pensada para destacar al Gigante de Alberdi con gran presencia visual y lectura de tribunas.',
        imagen: 'assets/img/products/belgrano-de-cordoba/julio-cesar-villagra/cover.webp',
        galeria: [
            'assets/img/products/belgrano-de-cordoba/julio-cesar-villagra/cover.webp',
            'assets/img/products/belgrano-de-cordoba/julio-cesar-villagra/gallery-01.webp',
            'assets/img/products/belgrano-de-cordoba/julio-cesar-villagra/gallery-02.webp',
            'assets/img/products/belgrano-de-cordoba/julio-cesar-villagra/gallery-03.webp',
            'assets/img/products/belgrano-de-cordoba/julio-cesar-villagra/gallery-04.webp',
            'assets/img/products/belgrano-de-cordoba/julio-cesar-villagra/gallery-05.webp'
        ]
    },
    {
        id: 8,
        estadio: 'Viejo Gasometro',
        club: 'San Lorenzo',
        escala: '1:600',
        precio: 191000,
        stock: 6,
        edicion: 'Arquitectura Moderna',
        material: 'Resina microtexturada',
        descripcion: 'Modelo de lineas limpias con estructura contemporanea y base lista para exhibicion.',
        imagen: 'assets/img/products/san-lorenzo/viejo-gasometro/cover.webp',
        galeria: [
            'assets/img/products/san-lorenzo/viejo-gasometro/cover.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-01.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-02.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-03.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-04.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-05.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-06.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-07.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-08.webp',
            'assets/img/products/san-lorenzo/viejo-gasometro/gallery-09.webp'
        ]
    },
    {
        id: 9,
        estadio: 'Frag. Pte. Sarmiento',
        club: 'Almirante Brown',
        escala: '1:620',
        precio: 186000,
        stock: 9,
        edicion: 'Coleccion Brasil',
        material: 'Composito premium',
        descripcion: 'Ideal para sumar una pieza con identidad barrial y una lectura muy marcada de sus tribunas.',
        imagen: 'assets/img/products/almirante-brown/frag-pte-sarmiento/cover.webp',
        galeria: [
            'assets/img/products/almirante-brown/frag-pte-sarmiento/cover.webp',
            'assets/img/products/almirante-brown/frag-pte-sarmiento/gallery-01.webp',
            'assets/img/products/almirante-brown/frag-pte-sarmiento/gallery-02.webp',
            'assets/img/products/almirante-brown/frag-pte-sarmiento/gallery-03.webp',
            'assets/img/products/almirante-brown/frag-pte-sarmiento/gallery-04.webp',
            'assets/img/products/almirante-brown/frag-pte-sarmiento/gallery-05.webp'
        ]
    },
    {
        id: 10,
        estadio: 'Tomas Adolfo Duco',
        club: 'Huracan',
        escala: '1:610',
        precio: 209000,
        stock: 4,
        edicion: 'Edicion Estreno',
        material: 'Resina + base negra',
        descripcion: 'Una maqueta del Palacio Duco con gran impacto visual y terminacion de alto contraste.',
        imagen: 'assets/img/products/huracan/tomas-adolfo-duco/cover.webp',
        galeria: [
            'assets/img/products/huracan/tomas-adolfo-duco/cover.webp',
            'assets/img/products/huracan/tomas-adolfo-duco/gallery-01.webp',
            'assets/img/products/huracan/tomas-adolfo-duco/gallery-02.webp',
            'assets/img/products/huracan/tomas-adolfo-duco/gallery-03.webp',
            'assets/img/products/huracan/tomas-adolfo-duco/gallery-04.webp'
        ]
    },
    {
        id: 11,
        estadio: 'Eva Peron',
        club: 'Sarmiento de Junin',
        escala: '1:630',
        precio: 179000,
        stock: 7,
        edicion: 'Clasicos De America',
        material: 'Poliresina',
        descripcion: 'Pieza sobria y elegante pensada para destacar historia, escala y volumen estructural.',
        imagen: 'assets/img/products/sarmiento-de-junin/eva-peron/cover.jpg',
        galeria: [
            'assets/img/products/sarmiento-de-junin/eva-peron/cover.jpg',
            'assets/img/products/sarmiento-de-junin/eva-peron/gallery-01.jpg',
            'assets/img/products/sarmiento-de-junin/eva-peron/gallery-02.jpg',
            'assets/img/products/sarmiento-de-junin/eva-peron/gallery-03.jpg',
            'assets/img/products/sarmiento-de-junin/eva-peron/gallery-04.jpg'
        ]
    },
    {
        id: 12,
        estadio: 'Republica de Mataderos',
        club: 'Nueva Chicago',
        escala: '1:640',
        precio: 195000,
        stock: 5,
        edicion: 'Serie Continental',
        material: 'Resina con acabado mate',
        descripcion: 'Pensado para colecciones amplias, con base firme y una lectura clara del estadio de Mataderos.',
        imagen: 'assets/img/products/nueva-chicago/republica-de-mataderos/cover.webp',
        galeria: [
            'assets/img/products/nueva-chicago/republica-de-mataderos/cover.webp',
            'assets/img/products/nueva-chicago/republica-de-mataderos/gallery-01.webp',
            'assets/img/products/nueva-chicago/republica-de-mataderos/gallery-02.webp',
            'assets/img/products/nueva-chicago/republica-de-mataderos/gallery-03.webp'
        ]
    },
    {
        id: 13,
        estadio: 'Diego Maradona',
        club: 'Argentinos Juniors',
        escala: '1:620',
        precio: 188000,
        stock: 6,
        edicion: 'Historia Sudamericana',
        material: 'Resina de alta definicion',
        descripcion: 'Una referencia historica llevada a maqueta con foco en proporciones y lectura arquitectonica.',
        imagen: 'assets/img/products/argentinos-juniors/diego-maradona/cover.webp',
        galeria: [
            'assets/img/products/argentinos-juniors/diego-maradona/cover.webp',
            'assets/img/products/argentinos-juniors/diego-maradona/gallery-01.webp',
            'assets/img/products/argentinos-juniors/diego-maradona/gallery-02.webp',
            'assets/img/products/argentinos-juniors/diego-maradona/gallery-03.webp',
            'assets/img/products/argentinos-juniors/diego-maradona/gallery-04.webp',
            'assets/img/products/argentinos-juniors/diego-maradona/gallery-05.webp'
        ]
    },
    {
        id: 14,
        estadio: 'Alfredo Beranger',
        club: 'Temperley',
        escala: '1:590',
        precio: 202000,
        stock: 5,
        edicion: 'Matchday Lights',
        material: 'Composito texturado',
        descripcion: 'Modelo del Beranger con presencia fuerte y terminaciones listas para vitrina.',
        imagen: 'assets/img/products/temperley/alfredo-beranger/cover.jpg',
        galeria: [
            'assets/img/products/temperley/alfredo-beranger/cover.jpg',
            'assets/img/products/temperley/alfredo-beranger/gallery-01.jpg',
            'assets/img/products/temperley/alfredo-beranger/gallery-02.jpg',
            'assets/img/products/temperley/alfredo-beranger/gallery-03.jpg',
            'assets/img/products/temperley/alfredo-beranger/gallery-04.jpg'
        ]
    },
    {
        id: 15,
        estadio: 'Gigante de Arroyito',
        club: 'Rosario Central',
        escala: '1:550',
        precio: 0,
        stock: 0,
        edicion: 'Proyecto Personalizado',
        material: 'Base premium + detalles a medida',
        descripcion: 'Referencia pensada para proyectos personalizados de estadios internacionales y pedidos especiales.',
        imagen: 'assets/img/products/rosario-central/gigante-de-arroyito/cover.jpg',
        galeria: [
            'assets/img/products/rosario-central/gigante-de-arroyito/cover.jpg',
            'assets/img/products/rosario-central/gigante-de-arroyito/gallery-01.jpg',
            'assets/img/products/rosario-central/gigante-de-arroyito/gallery-02.jpg',
            'assets/img/products/rosario-central/gigante-de-arroyito/gallery-03.jpg',
            'assets/img/products/rosario-central/gigante-de-arroyito/gallery-04.jpg',
            'assets/img/products/rosario-central/gigante-de-arroyito/gallery-05.jpg',
            'assets/img/products/rosario-central/gigante-de-arroyito/gallery-06.jpg',
            'assets/img/products/rosario-central/gigante-de-arroyito/gallery-07.jpg'
        ],
        referenciaPersonalizada: true
    },
    {
        id: 16,
        estadio: 'Olimpico de Tokio',
        club: 'Seleccion de Japon',
        escala: '1:550',
        precio: 0,
        stock: 0,
        edicion: 'Proyecto Personalizado',
        material: 'Base premium',
        descripcion: 'Replica a escala del iconico estadio olimpico, disenada para capturar su estructura arquitectonica unica.',
        imagen: 'assets/img/products/seleccion-de-japon/olimpico-de-tokio/cover.jpg',
        galeria: [
            'assets/img/products/seleccion-de-japon/olimpico-de-tokio/cover.jpg',
            'assets/img/products/seleccion-de-japon/olimpico-de-tokio/gallery-01.jpg',
            'assets/img/products/seleccion-de-japon/olimpico-de-tokio/gallery-02.jpg',
            'assets/img/products/seleccion-de-japon/olimpico-de-tokio/gallery-03.jpg',
            'assets/img/products/seleccion-de-japon/olimpico-de-tokio/gallery-04.jpg',
            'assets/img/products/seleccion-de-japon/olimpico-de-tokio/gallery-05.jpg',
            'assets/img/products/seleccion-de-japon/olimpico-de-tokio/gallery-06.jpg',
            'assets/img/products/seleccion-de-japon/olimpico-de-tokio/gallery-07.jpg'
        ],
        referenciaPersonalizada: true
    },
    {
        id: 17,
        estadio: 'Ciudad de Caseros',
        club: 'Est. de Caseros',
        escala: '1:550',
        precio: 0,
        stock: 0,
        edicion: 'Proyecto Personalizado',
        material: 'Base premium',
        descripcion: 'Referencia para el estadio del Pincha de Caseros, enfocada en los detalles caracteristicos de su arquitectura local.',
        imagen: 'assets/img/products/estudiantes-de-caseros/ciudad-de-caseros/cover.webp',
        galeria: [
            'assets/img/products/estudiantes-de-caseros/ciudad-de-caseros/cover.webp',
            'assets/img/products/estudiantes-de-caseros/ciudad-de-caseros/gallery-01.webp',
            'assets/img/products/estudiantes-de-caseros/ciudad-de-caseros/gallery-02.webp',
            'assets/img/products/estudiantes-de-caseros/ciudad-de-caseros/gallery-03.webp',
            'assets/img/products/estudiantes-de-caseros/ciudad-de-caseros/gallery-04.webp',
            'assets/img/products/estudiantes-de-caseros/ciudad-de-caseros/gallery-05.webp'
        ],
        referenciaPersonalizada: true
    },
    {
        id: 18,
        estadio: 'Monumental',
        club: 'River Plate',
        escala: '1:600',
        precio: 199000,
        stock: 4,
        edicion: 'Edicion Clasica',
        material: 'Polimero tecnico',
        descripcion: 'Version del Monumental anterior a la remodelacion, con foco en su silueta historica y lectura original de tribunas.',
        imagen: 'assets/img/products/river-plate/monumental/cover.jpg',
        galeria: [
            'assets/img/products/river-plate/monumental/cover.jpg',
            'assets/img/products/river-plate/monumental/gallery-01.jpg',
            'assets/img/products/river-plate/monumental/gallery-02.jpg',
            'assets/img/products/river-plate/monumental/gallery-03.jpg',
            'assets/img/products/river-plate/monumental/gallery-04.jpg',
            'assets/img/products/river-plate/monumental/gallery-05.jpg'
        ]
    },
    {
        id: 19,
        estadio: 'Jose Amalfitani',
        club: 'Velez Sarsfield',
        escala: '1:580',
        precio: 193000,
        stock: 5,
        edicion: 'Tribuna Clasica',
        material: 'Resina de alta definicion',
        descripcion: 'Una maqueta equilibrada para resaltar la estructura del Amalfitani y su presencia inconfundible en Liniers.',
        imagen: 'assets/img/products/velez-sarsfield/jose-amalfitani/cover.jpg',
        galeria: [
            'assets/img/products/velez-sarsfield/jose-amalfitani/cover.jpg',
            'assets/img/products/velez-sarsfield/jose-amalfitani/gallery-01.jpg',
            'assets/img/products/velez-sarsfield/jose-amalfitani/gallery-02.jpg',
            'assets/img/products/velez-sarsfield/jose-amalfitani/gallery-03.jpg',
            'assets/img/products/velez-sarsfield/jose-amalfitani/gallery-04.jpg',
            'assets/img/products/velez-sarsfield/jose-amalfitani/gallery-05.jpg'
        ]
    },
    {
        id: 20,
        estadio: 'Lusail Stadium',
        club: 'Qatar 2022',
        escala: '1:700',
        precio: 0,
        stock: 0,
        edicion: 'Proyecto Internacional',
        material: 'Base premium',
        descripcion: 'Referencia internacional pensada para pedidos especiales, con foco en la geometria exterior y la escala monumental del estadio.',
        imagen: 'assets/img/products/qatar/lusail-stadium/cover.jpg',
        galeria: [
            'assets/img/products/qatar/lusail-stadium/cover.jpg',
            'assets/img/products/qatar/lusail-stadium/gallery-01.jpg',
            'assets/img/products/qatar/lusail-stadium/gallery-02.jpg',
            'assets/img/products/qatar/lusail-stadium/gallery-03.jpg',
            'assets/img/products/qatar/lusail-stadium/gallery-04.jpg',
            'assets/img/products/qatar/lusail-stadium/gallery-05.jpg',
            'assets/img/products/qatar/lusail-stadium/gallery-06.jpg',
            'assets/img/products/qatar/lusail-stadium/gallery-07.jpg',
            'assets/img/products/qatar/lusail-stadium/gallery-08.jpg'
        ],
        referenciaPersonalizada: true
    },
    {
        id: 21,
        estadio: 'Ciudad de Vicente Lopez',
        club: 'Platense',
        escala: '1:610',
        precio: 184000,
        stock: 5,
        edicion: 'Barrio Edition',
        material: 'Resina satinada',
        descripcion: 'Modelo pensado para destacar la identidad barrial de Platense y la lectura compacta de su estadio.',
        imagen: 'assets/img/products/platense/ciudad-de-vicente-lopez/cover.jpg',
        galeria: [
            'assets/img/products/platense/ciudad-de-vicente-lopez/cover.jpg',
            'assets/img/products/platense/ciudad-de-vicente-lopez/gallery-01.jpg',
            'assets/img/products/platense/ciudad-de-vicente-lopez/gallery-02.jpg',
            'assets/img/products/platense/ciudad-de-vicente-lopez/gallery-03.jpg',
            'assets/img/products/platense/ciudad-de-vicente-lopez/gallery-04.jpg',
            'assets/img/products/platense/ciudad-de-vicente-lopez/gallery-05.jpg',
            'assets/img/products/platense/ciudad-de-vicente-lopez/gallery-06.jpg',
        ]
    },
    {
        id: 22,
        estadio: 'Florencio Sola',
        club: 'Banfield',
        escala: '1:600',
        precio: 187000,
        stock: 5,
        edicion: 'Sur Edition',
        material: 'Resina microtexturada',
        descripcion: 'Una pieza sobria para representar al Florencio Sola con buena lectura de tribunas y fachada principal.',
        imagen: 'assets/img/products/banfield/florencio-sola/cover.webp',
        galeria: [
            'assets/img/products/banfield/florencio-sola/cover.webp',
            'assets/img/products/banfield/florencio-sola/gallery-01.webp',
            'assets/img/products/banfield/florencio-sola/gallery-02.webp',
            'assets/img/products/banfield/florencio-sola/gallery-03.webp',
            'assets/img/products/banfield/florencio-sola/gallery-04.webp',
            'assets/img/products/banfield/florencio-sola/gallery-05.webp',
            'assets/img/products/banfield/florencio-sola/gallery-06.webp',
        ]
    },
    {
        id: 23,
        estadio: 'Marcelo Bielsa',
        club: 'Newell\'s Old Boys',
        escala: '1:500',
        precio: 195000,
        stock: 0,
        edicion: 'Edición Especial',
        material: 'Resina de alta definición',
        descripcion: 'Una representación detallada del estadio Marcelo Bielsa, hogar del Club Atlético Newell\'s Old Boys.',
        imagen: 'assets/img/products/newells/estadio-marcelo-bielsa/cover.webp',
        galeria: [
            'assets/img/products/newells/estadio-marcelo-bielsa/cover.webp',
            'assets/img/products/newells/estadio-marcelo-bielsa/gallery-01.webp',
            'assets/img/products/newells/estadio-marcelo-bielsa/gallery-02.webp',
            'assets/img/products/newells/estadio-marcelo-bielsa/gallery-03.webp',
            'assets/img/products/newells/estadio-marcelo-bielsa/gallery-04.webp',
            'assets/img/products/newells/estadio-marcelo-bielsa/gallery-05.webp'
        ]
    },
    {
        id: 24,
        estadio: 'Nuevo Gasometro',
        club: 'San Lorenzo',
        escala: '1:500',
        precio: 200000,
        stock: 0,
        edicion: 'Edición Especial',
        material: 'Resina de alta definición',
        descripcion: 'Una representación detallada del estadio Nuevo Gasómetro, hogar del Club San Lorenzo.',
        imagen: 'assets/img/products/san-lorenzo/nuevo-gasometro/cover.jpg',
        galeria: [
            'assets/img/products/san-lorenzo/nuevo-gasometro/cover.jpg',
            'assets/img/products/san-lorenzo/nuevo-gasometro/gallery-01.jpg',
            'assets/img/products/san-lorenzo/nuevo-gasometro/gallery-02.jpg',
            'assets/img/products/san-lorenzo/nuevo-gasometro/gallery-03.jpg',
            'assets/img/products/san-lorenzo/nuevo-gasometro/gallery-04.jpg',
            'assets/img/products/san-lorenzo/nuevo-gasometro/gallery-05.jpg'
        ]
    },
    {
        id: 25,
        estadio: 'Estadio Chacarita Juniors',
        club: 'Chacarita Juniors',
        escala: '1:500',
        precio: 210000,
        stock: 0,
        edicion: 'Edición Mini',
        material: 'Resina de alta definición',
        descripcion: 'Una representación a mini escala del estadio de Chacarita Jrs, hogar del Club Chacarita Juniors.',
        imagen: 'assets/img/products/chacarita/estadio-chacarita-juniors/cover.webp',
        galeria: [
            'assets/img/products/chacarita/estadio-chacarita-juniors/cover.webp',
            'assets/img/products/chacarita/estadio-chacarita-juniors/gallery-01.webp',
            'assets/img/products/chacarita/estadio-chacarita-juniors/gallery-02.webp',
            'assets/img/products/chacarita/estadio-chacarita-juniors/gallery-03.webp',
            'assets/img/products/chacarita/estadio-chacarita-juniors/gallery-04.webp',
            'assets/img/products/chacarita/estadio-chacarita-juniors/gallery-05.webp'
        ]
    },
    {
        id: 26,
        estadio: 'José Dellagiovanna',
        club: 'Tigre',
        escala: '1:500',
        precio: 220000,
        stock: 0,
        edicion: 'Edición Especial',
        material: 'Resina de alta definición',
        descripcion: 'Una representación detallada del estadio José Dellagiovanna, hogar del Club Atlético Tigre.',
        imagen: 'assets/img/products/tigre/estadio-tigre/cover.jpg',
        galeria: [
            'assets/img/products/tigre/estadio-tigre/cover.jpg',
            'assets/img/products/tigre/estadio-tigre/gallery-01.jpg',
            'assets/img/products/tigre/estadio-tigre/gallery-02.jpg',
            'assets/img/products/tigre/estadio-tigre/gallery-03.jpg',
            'assets/img/products/tigre/estadio-tigre/gallery-04.jpg',
            'assets/img/products/tigre/estadio-tigre/gallery-05.jpg'
        ]
    }
];
